<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NEWS</name>
   <tag></tag>
   <elementGuidId>f5320bde-e199-40a6-bbc6-2aab26afe95e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.news > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;trackURL('https://track.rediff.com/click?url=___https://www.rediff.com/news___&amp;position=nav2&amp;label=news&amp;c_type=edit_news&amp;property=hp_in_pc');return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41690268-beaa-4aab-a14e-039bac36a496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.rediff.com/news</value>
      <webElementGuid>f45229f6-cd08-4219-a2ef-f72daa884127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>trackURL('https://track.rediff.com/click?url=___https://www.rediff.com/news___&amp;position=nav2&amp;label=news&amp;c_type=edit_news&amp;property=hp_in_pc');return false;</value>
      <webElementGuid>4537b669-c059-4d67-bb0e-1f21d03cb3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEWS</value>
      <webElementGuid>4b42b660-2bba-469c-880a-533424cb1400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;navbar&quot;]/ul[@class=&quot;navbarul&quot;]/li[@class=&quot;news&quot;]/a[1]</value>
      <webElementGuid>6a43930f-a25d-4741-bb29-b2e2fd92e773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;trackURL('https://track.rediff.com/click?url=___https://www.rediff.com/news___&amp;position=nav2&amp;label=news&amp;c_type=edit_news&amp;property=hp_in_pc');return false;&quot;]</value>
      <webElementGuid>f0a22401-3df4-4180-9854-c738256b3f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NEWS')]</value>
      <webElementGuid>d9268de6-36f2-46e5-ae61-937f645a8ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.rediff.com/news')]</value>
      <webElementGuid>7ef2d514-8630-49e9-a607-fb08d4a9e39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>b939a193-b55a-4c61-826c-6713fda5930b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.rediff.com/news' and (text() = 'NEWS' or . = 'NEWS')]</value>
      <webElementGuid>6148b13c-7ede-483e-9ef7-04d4b57346e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
