<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_moneyiframe</name>
   <tag></tag>
   <elementGuidId>d9273b0d-b412-4131-8626-93391f108cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moneyiframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='moneyiframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>72ab68ab-a73d-4c72-a74a-df646da6380a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moneyiframe</value>
      <webElementGuid>60346d24-87e5-4805-8cf6-5a8a8bd52d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moneyiframe</value>
      <webElementGuid>32ae8668-ce2a-4ab2-8ee0-9a836bcdb79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>670</value>
      <webElementGuid>6170b0e7-907d-41ff-ab5a-c0785609aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>4c077350-65eb-40be-9959-4fc65d257090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://money.rediff.com/widget/moneywizwidget/rhome?src=rhome1</value>
      <webElementGuid>ac6b3ddb-c834-4ec7-98f4-e77b3620302d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rediff Money Widget</value>
      <webElementGuid>34a8584b-7657-444b-b187-2df43009f6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moneyiframe</value>
      <webElementGuid>d5f92135-b1ec-4b40-a114-fea603dd4d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moneyiframe&quot;)</value>
      <webElementGuid>b8932d36-8c3a-4d60-995a-7d8e1b224a40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='moneyiframe']</value>
      <webElementGuid>c9d4640d-7a54-4e5d-92bc-56a289d4c942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6665a6d9-8fb7-4d3f-a3d3-519adc3d3ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'moneyiframe' and @name = 'moneyiframe' and @src = 'https://money.rediff.com/widget/moneywizwidget/rhome?src=rhome1' and @title = 'Rediff Money Widget']</value>
      <webElementGuid>2c40a175-4ff4-444e-b6fc-2a172a2ad8b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
