<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_query</name>
   <tag></tag>
   <elementGuidId>4d9d40ec-7614-4c7d-87bd-3f117ae83850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#query</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='query']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49db9ca0-f758-4a70-bb54-d7d8cb485680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad0c70bc-30f4-4b64-9830-8838ec6f7388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>getquoteinput</value>
      <webElementGuid>4ab8998b-cece-4901-b6eb-aa2da72f4141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>db246fb3-d44c-46b5-b500-f00e924b7923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>b431ba43-5d4c-4e6d-b6cb-7776523e40ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>36001a8c-1def-4b4b-9e37-472d3ad8f763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter company or MF</value>
      <webElementGuid>deb2d0ff-96ad-4e6a-82e3-6c9df5b113c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;query&quot;)</value>
      <webElementGuid>af0e349c-7151-4000-a354-4b393a0580e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Rediff.com News  Rediffmail  Stock Quo_82c85b/iframe_moneyiframe</value>
      <webElementGuid>3ae94cf4-5202-4fee-a754-1469b07117ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='query']</value>
      <webElementGuid>ba6ef558-dffb-4200-8e87-d82984182a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='get_quote']/input</value>
      <webElementGuid>1d66b2fa-c1cf-4e15-94e5-780dad6d7238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>31b6dbe4-c931-4b95-baa4-31d27d860f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'query' and @id = 'query' and @placeholder = 'Enter company or MF']</value>
      <webElementGuid>80e33265-eda2-4962-af46-c2c8730bb674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
